apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-shared-workspace-pvc
  namespace: tekton
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi

  storageClassName: "gp2" 
  volumeName: tekton-shared-workspace-pv
