apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: entrypoint-task
spec:
  params:
    - name: payload
      description: Payload from Webhook
      type: string

    - name: filePayload
      description: File payload
      type: string
      default: payload.conf

    - name: fileGitHubEvent
      description: File GitHub event
      type: string
      default: gitHubEvent.conf

    - name: fileCustomData
      description: File custom data (data from webhook query string)
      type: string
      default: customData.conf

  workspaces:
    - name: github

  steps:
    - name: write-files
      image: quay.io/jberchez-redhat/custom-utils:v1.0
      script: |
        #! /usr/bin/env python3 

        import sys
        import json

        dir = "$(workspaces.github.path)"

        # GitHub payload
        payload = json.loads($(params.payload))

        try:
           f = open("{}/{}".format(dir, $(params.filePayload)),"w")
           f.write(payload)
           f.close()

           f = open("{}/{}".format(dir, $(params.fileGitHubEvent)),"w")
           f.write(payload['github_event_got'])
           f.close()

           if 'custom_data' in payload:
              f = open("{}/{}".format(dir, $(params.fileCustomData)),"w")
              f.write(payload['custom_data'])
              f.close()
        except Exception as e:
           print("[ERROR] {}".format(e))
           sys.exit(1)

        sys.exit(0)

    - name: show-files
      image: quay.io/jberchez-redhat/custom-utils:v1.0
      script: |
        #! /usr/bin/env bash

        set -e

        ls -ltr "$(workspaces.github.path)"

        if [[ -s "$(workspaces.github.path)/$(params.filePayload)" ]]; then
           cat "$(workspaces.github.path)/$(params.filePayload)"
        fi

        if [[ -s "$(workspaces.github.path)/$(params.fileGitHubEvent)" ]]; then
           cat "$(workspaces.github.path)/$(params.fileGitHubEvent)"
        fi

        if [[ -s "$(workspaces.github.path)/$(params.fileCustomData)" ]]; then
           cat "$(workspaces.github.path)/$(params.fileCustomData)"
        fi

        exit 0
